trigger: triage
title: Triage Issue
description: A template for responding to an issue
steps:
- type: form
  style: embedded
  body:
  - type: dropdown
    attributes:
      label: Status
      description: What is the status of triaging this issue?
      options:
      - label: 游릭 Complete
        value: 游릭
      - label: 游리 Started
        value: 游리
      - label: 游댮 Not Started
        value: 游댮
  - type: textarea
    attributes:
      label: Details
      description: What work has been completed so far?
      placeholder: "..."
  actions:
    submit: "Create"
    cancel: "Discard"
